#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil author:nil num:1 creator:nil timestamp:nil toc:nil html-style:nil

#+TITLE: Homework tasks
#+AUTHOR: Xiaohui Ellis

#+BEGIN_HTML
  <div class="github-fork-ribbon-wrapper left">
    <div class="github-fork-ribbon">
      <a href="https://github.com/stsb11/7-CS-Turing">Fork me on GitHub</a>
    </div>
  </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week1</a></li>
      <li><a href="2_Lesson.html">Week2</a></li>
      <li><a href="3_Lesson.html">Week3</a></li>
      <li><a href="4_Lesson.html">Week4</a></li>
      <li><a href="5_Lesson.html">Week5</a></li>
      <li><a href="6_Lesson.html">Week6</a></li
      <li><a href="homework.html">Homework</a></li>

    </ul>
  </div>
#+END_HTML
* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Homework
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Homework 1 - Programming Basics
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

- During week 1 you have played a text based game and had a look at the Python code.
- During week 2, you have learned and practiced using while loops. 
- For this assignment
  1. Write lines of code for the following:
     1. ask user to input a number and store the input in a variable
     2. convert the input number to an integer
     3. if the number is greater or equal to 10, output "It's double digit number at least", else output "It's a small number"
  2. Explain how this line of code works:
   #+BEGIN_SRC Python
   random.randrange(0,10)
   #+END_SRC
  3. The follow code is supposed to output numbers from 0 to 9. But it has an error in it. Please identify the error.
#+BEGIN_SRC Python
 while x < 10:
         x = 0
         print (x)
         x += 1
#+END_SRC
     

** Homework 2 - The range command
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

#+BEGIN_HTML
<!-- HTML generated using hilite.me --><div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><table style="text-align:left;"><tr><td><pre style="margin: 0; line-height: 125%">1
2</pre></td><td><pre style="margin: 0; line-height: 125%"><span style="color: #008800; font-weight: bold">for</span> I <span style="color: #000000; font-weight: bold">in</span> <span style="color: #007020">range</span>(<span style="color: #0000DD; font-weight: bold">5</span>):
    <span style="color: #008800; font-weight: bold">print</span>(<span style="background-color: #fff0f0">&quot;Welcome to the range&quot;</span>)
</pre></td></tr></table></div>

#+END_HTML

- The above code is a for loop - that is, the command indented underneath the =for i in range(5)= will be repeated. In this case, the =Welcome to the range= will be printed 5 times. Why?
- It is becasue the number of times a loop repeats is specified by the number given in the range(5).
- Range command works like this:
  1. =range(upToNumber)= - it produce a sequence of numbers from 0 up to BUT NOT equal to the upToNumber. For example, range(5) will produce: =0,1,2,3,4=, therefore, there are 5 numbers, for each number the loop going through, it prints out "Welcome to the range".
  2. =range(startNumber, upToNumber)= - it produces a sequence of numbers from startNumber to BUT NOT equal to the upToNumber. For example, range(3,8) will produce: =3,4,5,6,7=
  3. =range(startNumber, upToNumber, increaseBy)=- it produces a sequence of numbers from startNumber to BUT NOT equal to the upToNumber, each time the next number increase by the number specified by =increaseBy=. For example, range(2,10,2) will produce: =2,4,6,8=. 
- Your homework:
 1. What numbers are produced in this loop:
   #+BEGIN_HTML
<!-- HTML generated using hilite.me --><div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><table  style="text-align:left;"><tr><td><pre style="margin: 0; line-height: 125%">1
2</pre></td><td><pre style="margin: 0; line-height: 125%"><span style="color: #008800; font-weight: bold">for</span> i <span style="color: #000000; font-weight: bold">in</span> <span style="color: #007020">range</span>(<span style="color: #0000DD; font-weight: bold">10</span>, <span style="color: #0000DD; font-weight: bold">20</span>, <span style="color: #0000DD; font-weight: bold">2</span>):
    <span style="color: #008800; font-weight: bold">print</span>(i)
</pre></td></tr></table></div>


   #+END_HTML

 2. What numbers are produced in this loop:
   #+BEGIN_HTML
<!-- HTML generated using hilite.me --><div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><table style="text-align:left;"><tr><td><pre style="margin: 0; line-height: 125%">1
2</pre></td><td><pre style="margin: 0; line-height: 125%"><span style="color: #008800; font-weight: bold">for</span> i <span style="color: #000000; font-weight: bold">in</span> <span style="color: #007020">range</span>(<span style="color: #0000DD; font-weight: bold">100</span>, <span style="color: #0000DD; font-weight: bold">40</span>, <span style="color: #333333">-</span><span style="color: #0000DD; font-weight: bold">5</span>):
    <span style="color: #008800; font-weight: bold">print</span>(i)
</pre></td></tr></table></div>

   #+END_HTML

 3. write a for loop that will print out all positive whole numbers (integers) up to 100 that are divisible by 5.
	 
** Homework 3 - Literacy Task
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
- coming soon


